# Reducing angular derivative
gains:
  #pos: {x: 1.8, y: 1.8, z: 3.0}
  #vel: {x: 0.6, y: 0.6, z: 1.7}
  #pos: {x: 7.1, y: 7.1, z: 11.9}
  pos: {x: 9.0, y: 9.0, z: 14.0}
  vel: {x: 7.5, y: 7.5, z: 7.0}
  #pos: {x: 5.1, y: 5.1, z: 11.9} vicon
  #vel: {x: 1.0, y: 1.0, z: 6.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  ki:  {x: 0.00, y: 0.00, z: 0.008}
  # ki:  {x: 0.00, y: 0.00, z: 0.0}
corrections:
  kf: 0.0
  r: 0.0
  p: 0.0

