# This should contain tracker parameters

#QP Tracker/waypoints ONLY
qp_tracker:
  v_max: 2.0
  a_max: 4.0
  degree_optimize: 4
  x_max: 2.0
  x_min: -2.0
  y_max: 1.5
  y_min: -1.5
  z_max: 2
  z_min: 0.2

  #TAKE OFF ONLY
line_tracker_distance:
  default_v_des: 0.3
  default_a_des: 0.2
  epsilon: 0.1

  #GOTO/Land ONLY
line_tracker_min_jerk:
  default_v_des: 0.3
  default_a_des: 0.2
  default_yaw_v_des: 0.5
  default_yaw_a_des: 0.2

  #Circle/lissajous ONLY
trajectory_tracker:
  max_vel_des: 0.3
  max_acc_des: 0.2
